% plot_dtmf.m
% Reads dtmf.csv (generated by the C program) and plots the DFT modulus
% vs frequency for each of the 3 DTMF WAV files.
%
% For each file the C program must be run first to generate dtmf.csv,
% then this script is run once per file. It saves an SVG named after the
% detected key and appends the plot to dtmf_plots.pdf.
%
% Expected CSV format (no header row):
%   k, frequency (k*Δf), real part, imaginary part, modulus
%
% Usage (run once per WAV file, after running the C program):
%   >> plot_dtmf

clear; clc; close all;

%% Configuration
csv_file = 'dtmf.csv';
out_pdf  = 'dtmf_plots.pdf';
Fs       = 8000.0;   % Sampling frequency [Hz]

%% DTMF lookup table (for labelling the plot)
row_freq  = [697, 770, 852, 941];
col_freq  = [1209, 1336, 1477, 1633];
key_table = {'1','2','3','A'; ...
             '4','5','6','B'; ...
             '7','8','9','C'; ...
             '*','0','#','D'};
N = 256;

%% Load CSV
if ~isfile(csv_file)
    error('File "%s" not found. Run the C program first.', csv_file);
end

data = readmatrix(csv_file);
k    = data(:, 1);
freq = data(:, 2);
mag  = data(:, 5);

%% Only plot [0, Fs/2]
half = freq <= Fs / 2;
freq_plot = freq(half);
mag_plot  = mag(half);

%% Detect key from CSV magnitudes
% Compute expected bins
row_bins = round(row_freq * N / Fs) + 1;  % +1 for 1-based MATLAB indexing
col_bins = round(col_freq * N / Fs) + 1;

% Find dominant row and column bin
[~, best_row] = max(mag(row_bins));
[~, best_col] = max(mag(col_bins));
detected_key  = key_table{best_row, best_col};

fprintf('Tasto rilevato: %s\n', detected_key);

%% Plot
fig = figure('Name', sprintf('DTMF key=%s', detected_key), 'NumberTitle', 'off');

stem(freq_plot, mag_plot, 'filled', 'MarkerSize', 3, 'LineWidth', 1.0, ...
     'Color', [0.2 0.4 0.8]);

xlabel('Frequenza [Hz]');
ylabel('|X[k]|', 'Interpreter', 'tex');
title(sprintf('DFT DTMF — Tasto rilevato: %s  (%d Hz + %d Hz)', ...
      detected_key, row_freq(best_row), col_freq(best_col)));
grid on;
xlim([0 Fs/2]);

ax = gca;
ax.Toolbar.Visible = 'off';

%% Export
out_svg = sprintf('dtmf_key%s_plot.svg', detected_key);
exportgraphics(fig, out_svg, 'Resolution', 300);
exportgraphics(fig, out_pdf, 'Resolution', 300, 'Append', true);
fprintf('Plot salvato in "%s" e aggiunto a "%s".\n', out_svg, out_pdf);