% plot_rounded_quantization.m
% Reads rounded_quantization.csv (generated by the C program) and plots:
%   1. x_tilde vs x (quantized value vs original)
%   2. e vs x (quantization error vs original)
%
% Change n in the C program, recompile and run it, then run this script.
% It saves two SVGs named after the n value and appends each plot to its
% own PDF: rounded_quantization_xtilde_plots.pdf and rounded_quantization_error_plots.pdf.
%
% Expected CSV format (header row: x, X, xtilde, e):
%   x, X, xtilde, e
%
% Usage (run once per n value, after running the C program):
%   >> plot_rounded_quantization

clear; clc; close all;

%% Configuration
csv_file       = 'rounded_quantization.csv';
out_pdf_xtilde = 'rounded_quantization_xtilde_plots.pdf';
out_pdf_error  = 'rounded_quantization_error_plots.pdf';

%% Ask for n value (to name the SVGs and label the plots)
n = input('Inserire il valore di n usato nel programma C: ');

%% Load CSV
if ~isfile(csv_file)
    error('File "%s" not found. Run the C program first.', csv_file);
end

data   = readmatrix(csv_file, 'NumHeaderLines', 1);
x      = data(:, 1);
xtilde = data(:, 3);
e      = data(:, 4);

%% Plot 1: x_tilde vs x
fig1 = figure('Name', sprintf('Rounded Quantization n=%d - xtilde vs x', n), 'NumberTitle', 'off');

plot(x, xtilde, '.', 'MarkerSize', 4, 'Color', [0.55 0.2 0.8]);
hold on;
plot(x, x, '-', 'LineWidth', 1.0, 'Color', [0.1 0.7 0.4]);
hold off;

xlabel('$x$', 'Interpreter', 'latex');
ylabel('$\tilde{x}$', 'Interpreter', 'latex');
title(['Valore quantizzato (arrotondamento) x̃ in funzione di x — n = ' num2str(n)]);
legend({'$\tilde{x}$', '$y = x$'}, 'Location', 'northwest', 'Interpreter', 'latex');
grid on;
ylim([-0.1 0.1]);
xlim([-0.1 0.1]);

ax = gca;
ax.Toolbar.Visible = 'off';

%% Plot 2: e vs x
fig2 = figure('Name', sprintf('Rounded Quantization n=%d - error vs x', n), 'NumberTitle', 'off');

plot(x, e, '.', 'MarkerSize', 4, 'Color', [0.55 0.2 0.8]);
hold on;
yline(0, '-', 'Color', [0.1 0.7 0.4], 'LineWidth', 1.0);
hold off;

xlabel('$x$', 'Interpreter', 'latex');
ylabel('$e$', 'Interpreter', 'latex');
title(['Errore di quantizzazione (arrotondamento) e in funzione di x — n = ' num2str(n)]);
legend({'$e$', '$y = 0$'}, 'Location', 'northeast', 'Interpreter', 'latex');
grid on;
ylim([-0.1 0.1]);
xlim([-0.1 0.1]);

ax = gca;
ax.Toolbar.Visible = 'off';

%% Export
out_svg1 = sprintf('rounded_quantization_n%d_xtilde.svg', n);
out_svg2 = sprintf('rounded_quantization_n%d_error.svg', n);

exportgraphics(fig1, out_svg1, 'Resolution', 300);
exportgraphics(fig2, out_svg2, 'Resolution', 300);
exportgraphics(fig1, out_pdf_xtilde, 'Resolution', 300, 'Append', true);
exportgraphics(fig2, out_pdf_error,  'Resolution', 300, 'Append', true);

fprintf('Plot salvati in "%s", "%s".\n', out_svg1, out_svg2);
fprintf('Aggiunti a "%s" e "%s".\n', out_pdf_xtilde, out_pdf_error);