% plot_FIR.m
% Reads FIR.csv (generated by the C program) and plots the input x[n]
% and filtered output y[n] on the same figure vs time.
%
% Run the C program with the desired f0 value first, then run this script.
% It saves an SVG named after f0 and appends the plot to FIR_plots.pdf,
% so after both runs (f0=50 and f0=250) you have one PDF with both plots.
%
% Expected CSV format (no header row):
%   tn, x[n], y[n]
%
% Usage (run once per f0 value, after running the C program):
%   >> plot_FIR

clear; clc; close all;

%% Configuration
csv_file = 'FIR.csv';
out_pdf  = 'FIR_plots.pdf';

%% Ask for f0 value (to name the SVG and label the plot)
f0 = input('Inserire il valore di f0 usato nel programma C (Hz): ');

%% Load CSV
if ~isfile(csv_file)
    error('File "%s" not found. Run the C program first.', csv_file);
end

data = readmatrix(csv_file);
t    = data(:, 1);
x    = data(:, 2);
y    = data(:, 3);

%% Plot
fig = figure('Name', sprintf('FIR filter f0=%d Hz', f0), 'NumberTitle', 'off');

hold on;
plot(t, x, '-', 'LineWidth', 1.0, 'Color', [0.2 0.4 0.8], 'DisplayName', 'x[n]');
plot(t, y, '-', 'LineWidth', 1.0, 'Color', [0.85 0.2 0.2], 'DisplayName', 'y[n]');
hold off;

xlabel('Tempo [s]');
ylabel('Ampiezza');
title(['Filtro FIR in virgola fissa — f0 = ' num2str(f0) ' Hz']);
legend('Location', 'northeast');
grid on;
ylim([-0.6 0.6])
xlim([0 0.1])

ax = gca;
ax.Toolbar.Visible = 'off';

%% Export
out_svg = sprintf('FIR_f0%d_plot.svg', f0);
exportgraphics(fig, out_svg, 'Resolution', 300);
exportgraphics(fig, out_pdf, 'Resolution', 300, 'Append', true);
fprintf('Plot salvato in "%s" e aggiunto a "%s".\n', out_svg, out_pdf);