% plot_FFT_FIR.m
% Reads FFT_FIR.csv (generated by the C program) and plots the magnitude
% spectra of the input x[n] and filtered output y[n] on the same figure
% in the Nyquist window.
%
% Run the C program first to generate FFT_FIR.csv, then run this script.
% It saves one SVG and appends the plot to FFT_FIR_plots.pdf.
%
% Expected CSV format (no header row):
%   k, |X[k]|, |Y[k]|
%
% Usage:
%   >> plot_FFT_FIR

clear; clc; close all;

%% Configuration
csv_file = 'FFT_FIR.csv';
out_pdf  = 'FFT_FIR_plots.pdf';
Fs       = 1000;
N        = 1024;

%% Load CSV
if ~isfile(csv_file)
    error('File "%s" not found. Run the C program first.', csv_file);
end

data   = readmatrix(csv_file);
k      = data(:, 1);
mag_x  = data(:, 2);
mag_y  = data(:, 3);

%% Nyquist window: keep only k in [0, N/2]
freq      = k * Fs / N;
half      = freq <= Fs / 2;
freq_plot = freq(half);
magx_plot = mag_x(half);
magy_plot = mag_y(half);

%% Plot
fig = figure('Name', 'FFT FIR - Spectra', 'NumberTitle', 'off');

hold on;
stem(freq_plot, magx_plot, 'filled', 'MarkerSize', 2, 'LineWidth', 0.8, ...
     'Color', [0.2 0.4 0.8], 'DisplayName', '$|X[k]|$');
stem(freq_plot, magy_plot, 'filled', 'MarkerSize', 2, 'LineWidth', 0.8, ...
     'Color', [0.85 0.2 0.2], 'DisplayName', '$|Y[k]|$');
hold off;

xlabel('Frequenza [Hz]');
ylabel('Modulo');
title('Spettri di x[n] e y[n] - Filtro FIR in virgola fissa');
legend('Location', 'northeast', 'Interpreter', 'latex');
grid on;
xlim([0 Fs/2]);

ax = gca;
ax.Toolbar.Visible = 'off';

%% Export
out_svg = 'FFT_FIR_plot.svg';
exportgraphics(fig, out_svg, 'Resolution', 300);
exportgraphics(fig, out_pdf, 'Resolution', 300, 'Append', true);
fprintf('Plot salvato in "%s" e aggiunto a "%s".\n', out_svg, out_pdf);