% plot_gaussian_red_noise.m
% Reads gaussian_white_noise.csv and gaussian_red_noise.csv (generated by
% the C programs) and plots both power spectra on the same figure in the
% Nyquist window.
%
% Run both C programs first (Gaussian white and red noise, both Nx=10000),
% then run this script once.
%
% Expected CSV format (no header row):
%   k, S[k]
%
% Usage:
%   >> plot_gaussian_red_noise

clear; clc; close all;

%% Configuration
white_csv = 'gaussian_white_noise.csv';
red_csv   = 'gaussian_red_noise.csv';
out_pdf   = 'gaussian_red_noise_plot.pdf';
out_svg   = 'gaussian_red_noise_plot.svg';
Nx        = 10000;

%% Load CSVs
if ~isfile(white_csv)
    error('File "%s" not found. Run the Gaussian white noise C program first.', white_csv);
end
if ~isfile(red_csv)
    error('File "%s" not found. Run the Gaussian red noise C program first.', red_csv);
end

data_white = readmatrix(white_csv);
data_red   = readmatrix(red_csv);

k       = data_white(:, 1);
S_white = data_white(:, 2);
S_red   = data_red(:, 2);

%% Nyquist window
half    = k <= max(k) / 2;
k_plot  = k(half);
Sw_plot = S_white(half);
Sr_plot = S_red(half);

%% Plot
fig = figure('Name', 'Gaussian White vs Red Noise', 'NumberTitle', 'off');

hold on;
stem(k_plot, Sw_plot, 'filled', 'MarkerSize', 2, 'LineWidth', 0.8, ...
     'Color', [0.2 0.7 0.2], 'DisplayName', 'spettro rumore bianco gaussiano');
stem(k_plot, Sr_plot, 'filled', 'MarkerSize', 2, 'LineWidth', 0.8, ...
     'Color', [0.85 0.2 0.2], 'DisplayName', 'spettro rumore rosso gaussiano');
hold off;

xlabel('k');
ylabel('S[k]', 'Interpreter', 'tex');
title(sprintf('Spettri di potenza medi — Gaussiano, N_x = %d', Nx));
legend('Location', 'northeast');
grid on;
xlim([0 max(k_plot)]);
ylim([0 1000]);

ax = gca;
ax.Toolbar.Visible = 'off';

%% Export
exportgraphics(fig, out_svg, 'Resolution', 300);
exportgraphics(fig, out_pdf, 'Resolution', 300);
fprintf('Plot salvato in "%s" e "%s".\n', out_svg, out_pdf);