% plot_gaussian_white_noise.m
% Reads gaussian_white_noise.csv (generated by the C program) and plots the
% estimated power spectrum S[k] vs bin index k in the Nyquist window.
%
% Run the C program with the desired Nx value first, then run this script.
% It saves an SVG named after the Nx value and appends the plot to
% gaussian_white_noise_plots.pdf, so after all 5 runs you have one PDF.
%
% Expected CSV format (no header row):
%   k, S[k]
%
% Usage (run once per Nx value, after running the C program):
%   >> plot_gaussian_white_noise

clear; clc; close all;

%% Configuration
csv_file = 'gaussian_white_noise.csv';
out_pdf  = 'gaussian_white_noise_plots.pdf';

%% Ask for Nx value (to name the SVG and label the plot)
Nx = input('Inserire il valore di Nx usato per generare i campioni: ');

%% Load CSV
if ~isfile(csv_file)
    error('File "%s" not found. Run the C program first.', csv_file);
end

data = readmatrix(csv_file);
k    = data(:, 1);
S    = data(:, 2);

%% Nyquist window
half   = k <= max(k) / 2;
k_plot = k(half);
S_plot = S(half);

%% Plot
fig = figure('Name', sprintf('Gaussian White Noise Nx=%d', Nx), 'NumberTitle', 'off');

stem(k_plot, S_plot, 'filled', 'MarkerSize', 3, 'LineWidth', 1.0, ...
     'Color', [0.2 0.4 0.8]);

xlabel('Indice k');
ylabel('S[k]', 'Interpreter', 'tex');
title(sprintf('Spettro di potenza medio — Rumore bianco gaussiano, N_x = %d', Nx));
grid on;
xlim([0 max(k_plot)]);
ylim([0 420]);

ax = gca;
ax.Toolbar.Visible = 'off';

%% Export
out_svg = sprintf('gaussian_white_noise_Nx%d_plot.svg', Nx);
exportgraphics(fig, out_svg, 'Resolution', 300);
exportgraphics(fig, out_pdf, 'Resolution', 300, 'Append', true);
fprintf('Plot salvato in "%s" e aggiunto a "%s".\n', out_svg, out_pdf);